spring:
  datasource:
    url: jdbc:mysql://localhost:3306/demo?useSSL=false
    username: test
    password: test
    driver-class-name: com.mysql.cj.jdbc.Driver
    maximum-pool-size: 10
    minimum-idle: 10
    max-lifetime: 1800000
    idle-timeout: 600000
    connection-timeout: 30000
    connection-test-query: select 1 from dual