package com.demo.database.model;

import java.io.Serializable;

public class Demo implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.id
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    private Long id;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column demo.message
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    private String message;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table demo
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    private static final long serialVersionUID = 1L;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.id
     *
     * @return the value of demo.id
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.id
     *
     * @param id the value for demo.id
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column demo.message
     *
     * @return the value of demo.message
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    public String getMessage() {
        return message;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column demo.message
     *
     * @param message the value for demo.message
     *
     * @mbg.generated Wed May 29 02:09:50 JST 2024
     */
    public void setMessage(String message) {
        this.message = message == null ? null : message.trim();
    }
}